//! Python registrations for whole-history portfolio metrics.

use pyo3::prelude::*;

mod alpha;
mod annualized_return;
mod annualized_volatility;
mod average_drawdown;
mod average_loss;
mod average_win;
mod beta;
mod breakeven_rate;
mod calmar_ratio;
mod capture_ratio;
mod coefficient_of_determination;
mod common_sense_ratio;
mod composite_profitability_consistency_index;
mod conditional_drawdown_at_risk;
mod deflated_sharpe_ratio;
mod down_market_capture_ratio;
mod downside_deviation;
mod effective_number_of_bets;
mod entropic_value_at_risk;
mod expectancy;
mod exposure;
mod gain_to_pain_ratio;
mod gross_loss;
mod gross_profit;
mod historical_expected_shortfall;
mod historical_value_at_risk;
mod information_ratio;
mod kelly_criterion;
mod longest_losing_streak;
mod longest_winning_streak;
mod maximum_drawdown;
mod maximum_drawdown_duration;
mod metric_pipeline;
mod modified_sharpe_ratio;
mod net_profit;
mod omega_ratio;
mod pain_index;
mod pain_ratio;
mod parametric_expected_shortfall;
mod parametric_value_at_risk;
mod payoff_ratio;
mod probabilistic_sharpe_ratio;
mod profit_factor;
mod recovery_factor;
mod sharpe_ratio;
mod sortino_ratio;
mod stability_of_time_series;
mod system_quality_number;
mod tail_ratio;
mod total_return;
mod tracking_error;
mod treynor_ratio;
mod turnover;
mod ulcer_index;
mod ulcer_performance_index;
mod up_down_capture_ratio;
mod up_market_capture_ratio;
mod win_rate;

/// Register metric classes under `taflow._native.metrics`.
pub(crate) fn register(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<alpha::Alpha>()?;
    module.add_class::<average_drawdown::AverageDrawdown>()?;
    module.add_class::<average_loss::AverageLoss>()?;
    module.add_class::<average_win::AverageWin>()?;
    module.add_class::<annualized_return::AnnualizedReturn>()?;
    module.add_class::<annualized_volatility::AnnualizedVolatility>()?;
    module.add_class::<beta::Beta>()?;
    module.add_class::<breakeven_rate::BreakevenRate>()?;
    module.add_class::<calmar_ratio::CalmarRatio>()?;
    module.add_class::<capture_ratio::CaptureRatio>()?;
    module.add_class::<coefficient_of_determination::CoefficientOfDetermination>()?;
    module.add_class::<
        composite_profitability_consistency_index::CompositeProfitabilityConsistencyIndex,
    >()?;
    module.add_class::<conditional_drawdown_at_risk::ConditionalDrawdownAtRisk>()?;
    module.add_class::<common_sense_ratio::CommonSenseRatio>()?;
    module.add_class::<downside_deviation::DownsideDeviation>()?;
    module.add_class::<deflated_sharpe_ratio::DeflatedSharpeRatio>()?;
    module.add_class::<expectancy::Expectancy>()?;
    module.add_class::<effective_number_of_bets::EffectiveNumberOfBets>()?;
    module.add_class::<entropic_value_at_risk::EntropicValueAtRisk>()?;
    module.add_class::<exposure::Exposure>()?;
    module.add_class::<gain_to_pain_ratio::GainToPainRatio>()?;
    module.add_class::<gross_loss::GrossLoss>()?;
    module.add_class::<gross_profit::GrossProfit>()?;
    module.add_class::<down_market_capture_ratio::DownMarketCaptureRatio>()?;
    module.add_class::<historical_expected_shortfall::HistoricalExpectedShortfall>()?;
    module.add_class::<historical_value_at_risk::HistoricalValueAtRisk>()?;
    module.add_class::<information_ratio::InformationRatio>()?;
    module.add_class::<kelly_criterion::KellyCriterion>()?;
    module.add_class::<longest_losing_streak::LongestLosingStreak>()?;
    module.add_class::<longest_winning_streak::LongestWinningStreak>()?;
    module.add_class::<maximum_drawdown::MaximumDrawdown>()?;
    module.add_class::<maximum_drawdown_duration::MaximumDrawdownDuration>()?;
    module.add_class::<metric_pipeline::MetricPipeline>()?;
    module.add_class::<modified_sharpe_ratio::ModifiedSharpeRatio>()?;
    module.add_class::<net_profit::NetProfit>()?;
    module.add_class::<omega_ratio::OmegaRatio>()?;
    module.add_class::<pain_index::PainIndex>()?;
    module.add_class::<pain_ratio::PainRatio>()?;
    module.add_class::<payoff_ratio::PayoffRatio>()?;
    module.add_class::<parametric_expected_shortfall::ParametricExpectedShortfall>()?;
    module.add_class::<parametric_value_at_risk::ParametricValueAtRisk>()?;
    module.add_class::<profit_factor::ProfitFactor>()?;
    module.add_class::<probabilistic_sharpe_ratio::ProbabilisticSharpeRatio>()?;
    module.add_class::<recovery_factor::RecoveryFactor>()?;
    module.add_class::<sharpe_ratio::SharpeRatio>()?;
    module.add_class::<sortino_ratio::SortinoRatio>()?;
    module.add_class::<stability_of_time_series::StabilityOfTimeSeries>()?;
    module.add_class::<system_quality_number::SystemQualityNumber>()?;
    module.add_class::<tail_ratio::TailRatio>()?;
    module.add_class::<total_return::TotalReturn>()?;
    module.add_class::<tracking_error::TrackingError>()?;
    module.add_class::<treynor_ratio::TreynorRatio>()?;
    module.add_class::<turnover::Turnover>()?;
    module.add_class::<ulcer_index::UlcerIndex>()?;
    module.add_class::<ulcer_performance_index::UlcerPerformanceIndex>()?;
    module.add_class::<up_market_capture_ratio::UpMarketCaptureRatio>()?;
    module.add_class::<up_down_capture_ratio::UpDownCaptureRatio>()?;
    module.add_class::<win_rate::WinRate>()?;
    Ok(())
}
