#![allow(non_snake_case)]

use pyo3::prelude::*;

mod conversion;
mod func_api;
mod indicators;
mod metadata;
mod state_api;

/// Python module entry point for `taflow._native`.
#[pymodule]
fn _native(m: &Bound<'_, PyModule>) -> PyResult<()> {
    // 元数据 API
    m.add_function(wrap_pyfunction!(metadata::get_functions, m)?)?;
    m.add_function(wrap_pyfunction!(metadata::get_function_groups, m)?)?;

    // Unified indicator objects. Each TA binding lives in its own module and
    // owns its accumulated outputs so compute() never replays prior input.
    m.add_class::<indicators::ExponentialMovingAverage>()?;
    m.add_class::<indicators::CandleDoji>()?;
    m.add_class::<indicators::CandleTakuri>()?;
    m.add_class::<indicators::CandleClosingMarubozu>()?;
    m.add_class::<indicators::CandleEngulfing>()?;
    m.add_class::<indicators::CandleHammer>()?;
    m.add_class::<indicators::CandleHikkake>()?;
    m.add_class::<indicators::CandleHikkakeModified>()?;
    m.add_class::<indicators::CandleMarubozu>()?;
    m.add_class::<indicators::CandleLongLeggedDoji>()?;
    m.add_class::<indicators::CandleRickshawman>()?;
    m.add_class::<indicators::CandleHighWave>()?;
    m.add_class::<indicators::CandleDragonflyDoji>()?;
    m.add_class::<indicators::CandleGravestoneDoji>()?;
    m.add_class::<indicators::CandleShortLine>()?;
    m.add_class::<indicators::CandleSpinningTop>()?;
    m.add_class::<indicators::CandleLongLine>()?;
    m.add_class::<indicators::CandleDojiStar>()?;
    m.add_class::<indicators::CandleBeltHold>()?;
    m.add_class::<indicators::CandleUpDownSideGapThreeMethods>()?;
    m.add_class::<indicators::CandleStickSandwich>()?;
    m.add_class::<indicators::CandleTwoCrows>()?;
    m.add_class::<indicators::CandleThreeBlackCrows>()?;
    m.add_class::<indicators::CandleThreeInside>()?;
    m.add_class::<indicators::CandleThreeLineStrike>()?;
    m.add_class::<indicators::CandleThreeStarsInSouth>()?;
    m.add_class::<indicators::CandleThreeOutside>()?;
    m.add_class::<indicators::HilbertTransformDominantCyclePeriod>()?;
    m.add_class::<indicators::HilbertTransformDominantCyclePhase>()?;
    m.add_class::<indicators::HilbertTransformPhasor>()?;
    m.add_class::<indicators::HilbertTransformSineWave>()?;
    m.add_class::<indicators::HilbertTransformTrendMode>()?;
    m.add_class::<indicators::CommodityChannelIndex>()?;
    m.add_class::<indicators::MoneyFlowIndex>()?;
    m.add_class::<indicators::PlusDirectionalIndicator>()?;
    m.add_class::<indicators::PlusDirectionalMovement>()?;
    m.add_class::<indicators::MinusDirectionalIndicator>()?;
    m.add_class::<indicators::MinusDirectionalMovement>()?;
    m.add_class::<indicators::TripleExponentialRateOfChange>()?;
    m.add_class::<indicators::UltimateOscillator>()?;
    m.add_class::<indicators::LagOperator>()?;
    m.add_class::<indicators::LogReturnOperator>()?;
    m.add_class::<indicators::CumsumOperator>()?;
    m.add_class::<indicators::CumprodOperator>()?;
    m.add_class::<indicators::RollingMedianOperator>()?;
    m.add_class::<indicators::RollingModeOperator>()?;
    m.add_class::<indicators::RollingQuantileOperator>()?;
    m.add_class::<indicators::RollingPercentileOperator>()?;
    m.add_class::<indicators::RollingRankOperator>()?;
    m.add_class::<indicators::RollingZscoreOperator>()?;
    m.add_class::<indicators::RollingSkewOperator>()?;
    m.add_class::<indicators::RollingKurtosisOperator>()?;
    m.add_class::<indicators::RollingIqrOperator>()?;
    m.add_class::<indicators::RollingCovOperator>()?;
    m.add_class::<indicators::RollingWinsorizeOperator>()?;
    m.add_class::<indicators::EwmVarOperator>()?;
    m.add_class::<indicators::EwmStdOperator>()?;
    m.add_class::<indicators::EwmCovOperator>()?;
    m.add_class::<indicators::EwmCorrOperator>()?;
    m.add_class::<indicators::CummaxOperator>()?;
    m.add_class::<indicators::CumminOperator>()?;
    m.add_class::<indicators::DrawdownOperator>()?;
    m.add_class::<indicators::RollingSharpeOperator>()?;
    m.add_class::<indicators::RollingSortinoOperator>()?;
    m.add_class::<indicators::RollingCalmarOperator>()?;
    m.add_class::<indicators::HmaOperator>()?;
    m.add_class::<indicators::VwmaOperator>()?;
    m.add_class::<indicators::ZlemaOperator>()?;
    m.add_class::<indicators::AlmaOperator>()?;
    m.add_class::<indicators::TsiOperator>()?;
    m.add_class::<indicators::AwesomeOscillatorOperator>()?;
    m.add_class::<indicators::FisherTransformOperator>()?;
    m.add_class::<indicators::DonchianOperator>()?;
    m.add_class::<indicators::UlcerIndexOperator>()?;
    m.add_class::<indicators::KeltnerChannelsOperator>()?;
    m.add_class::<indicators::ChaikinVolatilityOperator>()?;
    m.add_class::<indicators::CrossoverOperator>()?;
    m.add_class::<indicators::CrossunderOperator>()?;
    m.add_class::<indicators::CrossOperator>()?;
    m.add_class::<indicators::RisingOperator>()?;
    m.add_class::<indicators::FallingOperator>()?;
    m.add_class::<indicators::VwapOperator>()?;
    m.add_class::<indicators::ForceIndexOperator>()?;
    m.add_class::<indicators::EaseOfMovementOperator>()?;
    m.add_class::<indicators::HigherHighOperator>()?;
    m.add_class::<indicators::LowerLowOperator>()?;
    m.add_class::<indicators::InsideBarOperator>()?;
    m.add_class::<indicators::OutsideBarOperator>()?;
    m.add_class::<indicators::GapUpOperator>()?;
    m.add_class::<indicators::GapDownOperator>()?;
    m.add_class::<indicators::BarsSinceOperator>()?;
    m.add_class::<indicators::ValueWhenOperator>()?;
    m.add_class::<indicators::HighestSinceOperator>()?;
    m.add_class::<indicators::LowestSinceOperator>()?;
    m.add_class::<indicators::SignalDelayOperator>()?;
    m.add_class::<indicators::PositionHoldOperator>()?;
    m.add_class::<indicators::EntryExitOperator>()?;
    m.add_class::<indicators::SwingHighLowOperator>()?;
    m.add_class::<indicators::SessionExtremaOperator>()?;
    m.add_class::<indicators::PreviousHighLowOperator>()?;
    m.add_class::<indicators::SessionsOperator>()?;
    m.add_class::<indicators::RetracementsOperator>()?;
    m.add_class::<indicators::CloseToCloseSigmaOperator>()?;
    m.add_class::<indicators::ParkinsonOperator>()?;
    m.add_class::<indicators::GarmanKlassOperator>()?;
    m.add_class::<indicators::RogersSatchellOperator>()?;
    m.add_class::<indicators::GkYangZhangOperator>()?;
    m.add_class::<indicators::YangZhangOperator>()?;
    m.add_class::<indicators::AdvOperator>()?;
    m.add_class::<indicators::AmihudOperator>()?;
    m.add_class::<indicators::RollSpreadOperator>()?;
    m.add_class::<indicators::OuHalfLifeOperator>()?;
    m.add_class::<indicators::CusumOperator>()?;
    m.add_class::<indicators::SpreadZscoreOperator>()?;
    m.add_class::<indicators::FracDiffOperator>()?;
    m.add_class::<indicators::KalmanHedgeRatioOperator>()?;
    m.add_class::<indicators::SupertrendOperator>()?;
    m.add_class::<indicators::IchimokuOperator>()?;
    m.add_class::<indicators::SqueezeOperator>()?;
    m.add_class::<indicators::SqueezeProOperator>()?;
    m.add_class::<indicators::StcOperator>()?;
    m.add_class::<indicators::VortexOperator>()?;
    m.add_class::<indicators::KstOperator>()?;
    m.add_class::<indicators::MassIndexOperator>()?;
    m.add_class::<indicators::DpoOperator>()?;
    m.add_class::<indicators::CmfOperator>()?;
    m.add_class::<indicators::VptOperator>()?;
    m.add_class::<indicators::NviOperator>()?;
    m.add_class::<indicators::PviOperator>()?;
    m.add_class::<indicators::McgdOperator>()?;
    m.add_class::<indicators::ActiveZoneListOperator>()?;
    m.add_class::<indicators::FvgOperator>()?;
    m.add_class::<indicators::BosChochOperator>()?;
    m.add_class::<indicators::ObOperator>()?;
    m.add_class::<indicators::LiquidityOperator>()?;
    m.add_class::<indicators::EqualHighsLowsOperator>()?;
    m.add_class::<indicators::HedgeRatioOperator>()?;
    m.add_class::<indicators::RollingEntropyOperator>()?;
    m.add_class::<indicators::RollingAutocorrOperator>()?;
    m.add_class::<indicators::HurstOperator>()?;
    m.add_class::<indicators::FractalDimensionOperator>()?;
    m.add_class::<indicators::RollingAlphaOperator>()?;
    m.add_class::<indicators::RollingInformationRatioOperator>()?;
    m.add_class::<indicators::CandleThreeWhiteSoldiers>()?;
    m.add_class::<indicators::CandleAbandonedBaby>()?;
    m.add_class::<indicators::CandleAdvanceBlock>()?;
    m.add_class::<indicators::CandleBreakaway>()?;
    m.add_class::<indicators::CandleConcealBabySwall>()?;
    m.add_class::<indicators::CandleCounterAttack>()?;
    m.add_class::<indicators::CandleDarkCloudCover>()?;
    m.add_class::<indicators::CandleEveningDojiStar>()?;
    m.add_class::<indicators::CandleEveningStar>()?;
    m.add_class::<indicators::CandleGapSideSideWhite>()?;
    m.add_class::<indicators::CandleHangingMan>()?;
    m.add_class::<indicators::CandleHarami>()?;
    m.add_class::<indicators::CandleHaramiCross>()?;
    m.add_class::<indicators::CandleHomingPigeon>()?;
    m.add_class::<indicators::CandleIdenticalThreeCrows>()?;
    m.add_class::<indicators::CandleInNeck>()?;
    m.add_class::<indicators::CandleInvertedHammer>()?;
    m.add_class::<indicators::CandleKicking>()?;
    m.add_class::<indicators::CandleKickingByLength>()?;
    m.add_class::<indicators::CandleLadderBottom>()?;
    m.add_class::<indicators::CandleMatchingLow>()?;
    m.add_class::<indicators::CandleMatHold>()?;
    m.add_class::<indicators::CandleMorningDojiStar>()?;
    m.add_class::<indicators::CandleMorningStar>()?;
    m.add_class::<indicators::CandleOnNeck>()?;
    m.add_class::<indicators::CandlePiercing>()?;
    m.add_class::<indicators::CandleRiseFallThreeMethods>()?;
    m.add_class::<indicators::CandleSeparatingLines>()?;
    m.add_class::<indicators::CandleShootingStar>()?;
    m.add_class::<indicators::CandleStalledPattern>()?;
    m.add_class::<indicators::CandleTasukiGap>()?;
    m.add_class::<indicators::CandleThrusting>()?;
    m.add_class::<indicators::CandleTriStar>()?;
    m.add_class::<indicators::CandleUniqueThreeRiver>()?;
    m.add_class::<indicators::CandleUpsideGapTwoCrows>()?;

    // Transitional state classes remain available while their indicators move
    // to the unified object surface above.
    m.add_class::<state_api::StatefulSma>()?;
    m.add_class::<state_api::StatefulEma>()?;
    m.add_class::<state_api::StatefulWma>()?;
    m.add_class::<state_api::StatefulDema>()?;
    m.add_class::<state_api::StatefulTema>()?;
    m.add_class::<state_api::StatefulTrima>()?;
    m.add_class::<state_api::StatefulMidpoint>()?;
    m.add_class::<state_api::StatefulMidprice>()?;
    m.add_class::<state_api::StatefulRsi>()?;
    m.add_class::<state_api::StatefulImi>()?;
    m.add_class::<state_api::StatefulMom>()?;
    m.add_class::<state_api::StatefulRoc>()?;
    m.add_class::<state_api::StatefulRocp>()?;
    m.add_class::<state_api::StatefulRocr>()?;
    m.add_class::<state_api::StatefulRocr100>()?;
    m.add_class::<state_api::StatefulMax>()?;
    m.add_class::<state_api::StatefulMaxindex>()?;
    m.add_class::<state_api::StatefulMin>()?;
    m.add_class::<state_api::StatefulMinindex>()?;
    m.add_class::<state_api::StatefulSum>()?;
    m.add_class::<state_api::StatefulMinmax>()?;
    m.add_class::<state_api::StatefulMinmaxindex>()?;
    m.add_class::<state_api::StatefulAvgdev>()?;
    m.add_class::<state_api::StatefulVar>()?;
    m.add_class::<state_api::StatefulStddev>()?;
    m.add_class::<state_api::StatefulBeta>()?;
    m.add_class::<state_api::StatefulCorrel>()?;
    m.add_class::<state_api::StatefulLinearreg>()?;
    m.add_class::<state_api::StatefulLinearregSlope>()?;
    m.add_class::<state_api::StatefulLinearregIntercept>()?;
    m.add_class::<state_api::StatefulLinearregAngle>()?;
    m.add_class::<state_api::StatefulTsf>()?;
    m.add_class::<state_api::StatefulCmo>()?;
    m.add_class::<state_api::StatefulRelativeMomentumIndex>()?;
    m.add_class::<state_api::StatefulVariableIndexDynamicAverage>()?;
    m.add_class::<state_api::StatefulLaguerreRelativeStrengthIndex>()?;
    m.add_class::<state_api::StatefulEvenBetterSinewave>()?;
    m.add_class::<state_api::StatefulJurikMovingAverage>()?;
    m.add_class::<state_api::StatefulSmoothedTrendChannel>()?;
    m.add_class::<state_api::StatefulPremiumDiscount>()?;
    m.add_class::<state_api::StatefulHeikinAshi>()?;
    m.add_class::<state_api::StatefulFibonacciRetracement>()?;
    m.add_class::<state_api::StatefulOpeningRange>()?;
    m.add_class::<state_api::StatefulSessionVolumeLevels>()?;
    m.add_class::<state_api::StatefulKlingerVolumeOscillator>()?;
    m.add_class::<state_api::StatefulCci>()?;
    m.add_class::<state_api::StatefulKama>()?;
    m.add_class::<state_api::StatefulAd>()?;
    m.add_class::<state_api::StatefulAdosc>()?;
    m.add_class::<state_api::StatefulObv>()?;
    m.add_class::<state_api::StatefulBop>()?;
    m.add_class::<state_api::StatefulWillr>()?;
    m.add_class::<state_api::StatefulAroon>()?;
    m.add_class::<state_api::StatefulAroonosc>()?;
    m.add_class::<state_api::StatefulAvgprice>()?;
    m.add_class::<state_api::StatefulMedprice>()?;
    m.add_class::<state_api::StatefulTypprice>()?;
    m.add_class::<state_api::StatefulWclprice>()?;
    m.add_class::<state_api::StatefulAcos>()?;
    m.add_class::<state_api::StatefulAsin>()?;
    m.add_class::<state_api::StatefulAtan>()?;
    m.add_class::<state_api::StatefulCeil>()?;
    m.add_class::<state_api::StatefulCos>()?;
    m.add_class::<state_api::StatefulCosh>()?;
    m.add_class::<state_api::StatefulExp>()?;
    m.add_class::<state_api::StatefulFloor>()?;
    m.add_class::<state_api::StatefulLn>()?;
    m.add_class::<state_api::StatefulLog10>()?;
    m.add_class::<state_api::StatefulSin>()?;
    m.add_class::<state_api::StatefulSinh>()?;
    m.add_class::<state_api::StatefulSqrt>()?;
    m.add_class::<state_api::StatefulTan>()?;
    m.add_class::<state_api::StatefulTanh>()?;
    m.add_class::<state_api::StatefulAdd>()?;
    m.add_class::<state_api::StatefulSub>()?;
    m.add_class::<state_api::StatefulMult>()?;
    m.add_class::<state_api::StatefulDiv>()?;
    m.add_class::<state_api::StatefulAtr>()?;
    m.add_class::<state_api::StatefulTrange>()?;
    m.add_class::<state_api::StatefulNatr>()?;
    m.add_class::<state_api::StatefulMacd>()?;
    m.add_class::<state_api::StatefulMacdExt>()?;
    m.add_class::<state_api::StatefulMavp>()?;
    m.add_class::<state_api::StatefulHtTrendline>()?;
    m.add_class::<state_api::StatefulAdx>()?;
    m.add_class::<state_api::StatefulAdxr>()?;
    m.add_class::<state_api::StatefulDx>()?;
    m.add_class::<state_api::StatefulMacdFix>()?;
    m.add_class::<state_api::StatefulStoch>()?;
    m.add_class::<state_api::StatefulStochf>()?;
    m.add_class::<state_api::StatefulStochrsi>()?;
    m.add_class::<state_api::StatefulMama>()?;
    m.add_class::<state_api::StatefulT3>()?;
    m.add_class::<state_api::StatefulApo>()?;
    m.add_class::<state_api::StatefulPpo>()?;
    m.add_class::<state_api::StatefulMa>()?;
    m.add_class::<state_api::StatefulBbands>()?;
    m.add_class::<state_api::StatefulAccbands>()?;
    m.add_class::<state_api::StatefulSar>()?;
    m.add_class::<state_api::StatefulSarext>()?;

    // ===== Overlap Studies =====
    m.add_function(wrap_pyfunction!(func_api::ACCBANDS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::EMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::WMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::DEMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TEMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TRIMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::KAMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::T3, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MAMA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::BBANDS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SAREXT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MIDPOINT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MIDPRICE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MAVP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::HT_TRENDLINE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MA, m)?)?;

    // ===== Momentum Indicators =====
    m.add_function(wrap_pyfunction!(func_api::IMI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::RSI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MACD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MACDEXT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MACDFIX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::STOCH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::STOCHF, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::STOCHRSI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ADX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ADXR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CCI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MOM, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ROC, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ROCP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ROCR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ROCR100, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::WILLR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::APO, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::PPO, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::BOP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CMO, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::AROON, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::AROONOSC, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MFI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TRIX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ULTOSC, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::DX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::PLUS_DI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MINUS_DI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::PLUS_DM, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MINUS_DM, m)?)?;

    // ===== Volatility =====
    m.add_function(wrap_pyfunction!(func_api::ATR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::NATR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TRANGE, m)?)?;

    // ===== Volume =====
    m.add_function(wrap_pyfunction!(func_api::AD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ADOSC, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::OBV, m)?)?;

    // ===== Price Transform =====
    m.add_function(wrap_pyfunction!(func_api::AVGPRICE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MEDPRICE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TYPPRICE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::WCLPRICE, m)?)?;

    // ===== Statistic =====
    m.add_function(wrap_pyfunction!(func_api::AVGDEV, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::STDDEV, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::VAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::BETA, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CORREL, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LINEARREG, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LINEARREG_SLOPE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LINEARREG_INTERCEPT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LINEARREG_ANGLE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TSF, m)?)?;

    // ===== Math Transform =====
    m.add_function(wrap_pyfunction!(func_api::ACOS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ASIN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::ATAN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CEIL, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::COS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::COSH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::EXP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::FLOOR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::LOG10, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SIN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SINH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SQRT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TAN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::TANH, m)?)?;

    // ===== Math Operators =====
    m.add_function(wrap_pyfunction!(func_api::ADD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SUB, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MULT, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::DIV, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MAX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MAXINDEX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MIN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MININDEX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::SUM, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MINMAX, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::MINMAXINDEX, m)?)?;

    // ===== Cycle Indicators =====
    m.add_function(wrap_pyfunction!(func_api::HT_DCPERIOD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::HT_DCPHASE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::HT_PHASOR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::HT_SINE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::HT_TRENDMODE, m)?)?;

    // ===== Pattern Recognition =====
    m.add_function(wrap_pyfunction!(func_api::CDLDOJI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHAMMER, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLENGULFING, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL2CROWS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3BLACKCROWS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3INSIDE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3LINESTRIKE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3OUTSIDE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3STARSINSOUTH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDL3WHITESOLDIERS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLABANDONEDBABY, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLADVANCEBLOCK, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLBELTHOLD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLBREAKAWAY, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLCLOSINGMARUBOZU, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLCONCEALBABYSWALL, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLCOUNTERATTACK, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLDARKCLOUDCOVER, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLDOJISTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLDRAGONFLYDOJI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLEVENINGDOJISTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLEVENINGSTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLGAPSIDESIDEWHITE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLGRAVESTONEDOJI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHANGINGMAN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHARAMI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHARAMICROSS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHIGHWAVE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHIKKAKE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHIKKAKEMOD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLHOMINGPIGEON, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLIDENTICAL3CROWS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLINNECK, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLINVERTEDHAMMER, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLKICKING, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLKICKINGBYLENGTH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLLADDERBOTTOM, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLLONGLEGGEDDOJI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLLONGLINE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLMARUBOZU, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLMATCHINGLOW, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLMATHOLD, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLMORNINGDOJISTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLMORNINGSTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLONNECK, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLPIERCING, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLRICKSHAWMAN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLRISEFALL3METHODS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSEPARATINGLINES, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSHOOTINGSTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSHORTLINE, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSPINNINGTOP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSTALLEDPATTERN, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLSTICKSANDWICH, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLTAKURI, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLTASUKIGAP, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLTHRUSTING, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLTRISTAR, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLUNIQUE3RIVER, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLUPSIDEGAP2CROWS, m)?)?;
    m.add_function(wrap_pyfunction!(func_api::CDLXSIDEGAP3METHODS, m)?)?;

    Ok(())
}
