"""Stateful O(1)-per-bar indicators for historical backfill and live feeds.

The compatibility :mod:`taflow.talib.stream` module mirrors TA-Lib's latest-value API and
recomputes the supplied history.  This module owns indicator state instead:

    from taflow.talib.state import RSI
    rsi = RSI(14)
    rsi.extend(history)
    latest = rsi.append(next_close)

``append`` returns ``None`` until the TA-Lib-compatible warm-up is complete.
``extend`` returns a NumPy array aligned to its input, with ``NaN`` during
warm-up.
"""

from taflow._native import (
    StatefulAccbands as ACCBANDS,
    StatefulAcos as ACOS,
    StatefulAd as AD,
    StatefulAdosc as ADOSC,
    StatefulAdd as ADD,
    StatefulAsin as ASIN,
    StatefulAtan as ATAN,
    StatefulApo as APO,
    StatefulAtr as ATR,
    StatefulAroon as AROON,
    StatefulAroonosc as AROONOSC,
    StatefulAvgprice as AVGPRICE,
    StatefulBeta as BETA,
    StatefulBbands as BBANDS,
    StatefulBop as BOP,
    StatefulAvgdev as AVGDEV,
    StatefulCeil as CEIL,
    StatefulCos as COS,
    StatefulCosh as COSH,
    StatefulCmo as CMO,
    StatefulCorrel as CORREL,
    StatefulDema as DEMA,
    StatefulDiv as DIV,
    StatefulNatr as NATR,
    StatefulObv as OBV,
    StatefulEma as EMA,
    StatefulExp as EXP,
    StatefulFloor as FLOOR,
    StatefulLn as LN,
    StatefulKama as KAMA,
    StatefulImi as IMI,
    StatefulHtTrendline as HT_TRENDLINE,
    StatefulLog10 as LOG10,
    StatefulLinearreg as LINEARREG,
    StatefulLinearregAngle as LINEARREG_ANGLE,
    StatefulLinearregIntercept as LINEARREG_INTERCEPT,
    StatefulLinearregSlope as LINEARREG_SLOPE,
    StatefulMacd as MACD,
    StatefulMacdExt as MACDEXT,
    StatefulMacdFix as MACDFIX,
    StatefulMavp as MAVP,
    StatefulMa as MA,
    StatefulMama as MAMA,
    StatefulMax as MAX,
    StatefulMaxindex as MAXINDEX,
    StatefulMedprice as MEDPRICE,
    StatefulMidpoint as MIDPOINT,
    StatefulMidprice as MIDPRICE,
    StatefulMin as MIN,
    StatefulMinindex as MININDEX,
    StatefulMinmax as MINMAX,
    StatefulMinmaxindex as MINMAXINDEX,
    StatefulMom as MOM,
    StatefulMult as MULT,
    StatefulRoc as ROC,
    StatefulRocp as ROCP,
    StatefulRocr as ROCR,
    StatefulRocr100 as ROCR100,
    StatefulRsi as RSI,
    StatefulSar as SAR,
    StatefulSarext as SAREXT,
    StatefulPpo as PPO,
    StatefulSin as SIN,
    StatefulSinh as SINH,
    StatefulSma as SMA,
    StatefulSqrt as SQRT,
    StatefulStddev as STDDEV,
    StatefulStoch as STOCH,
    StatefulStochf as STOCHF,
    StatefulStochrsi as STOCHRSI,
    StatefulSub as SUB,
    StatefulSum as SUM,
    StatefulTan as TAN,
    StatefulTanh as TANH,
    StatefulT3 as T3,
    StatefulTema as TEMA,
    StatefulTrange as TRANGE,
    StatefulTrima as TRIMA,
    StatefulTsf as TSF,
    StatefulTypprice as TYPPRICE,
    StatefulVar as VAR,
    StatefulWclprice as WCLPRICE,
    StatefulWma as WMA,
    StatefulWillr as WILLR,
)

__all__ = [
    "SMA",
    "EMA",
    "WMA",
    "DEMA",
    "TEMA",
    "TRIMA",
    "MIDPOINT",
    "MIDPRICE",
    "RSI",
    "MOM",
    "ROC",
    "ROCP",
    "ROCR",
    "ROCR100",
    "AVGPRICE",
    "MEDPRICE",
    "TYPPRICE",
    "WCLPRICE",
    "ACOS",
    "ASIN",
    "ATAN",
    "CEIL",
    "COS",
    "COSH",
    "EXP",
    "FLOOR",
    "LN",
    "LOG10",
    "SIN",
    "SINH",
    "SQRT",
    "TAN",
    "TANH",
    "ADD",
    "SUB",
    "MULT",
    "DIV",
    "MAX",
    "MAXINDEX",
    "MIN",
    "MININDEX",
    "SUM",
    "MINMAX",
    "MINMAXINDEX",
    "AVGDEV",
    "STDDEV",
    "STOCH",
    "STOCHF",
    "STOCHRSI",
    "VAR",
    "BETA",
    "CORREL",
    "LINEARREG",
    "LINEARREG_SLOPE",
    "LINEARREG_INTERCEPT",
    "LINEARREG_ANGLE",
    "TSF",
    "CMO",
    "KAMA",
    "IMI",
    "HT_TRENDLINE",
    "AD",
    "ADOSC",
    "OBV",
    "BOP",
    "WILLR",
    "AROON",
    "AROONOSC",
    "ATR",
    "NATR",
    "TRANGE",
    "MACD",
    "MACDEXT",
    "MACDFIX",
    "MAVP",
    "MAMA",
    "T3",
    "APO",
    "PPO",
    "MA",
    "BBANDS",
    "ACCBANDS",
    "SAR",
    "SAREXT",
]
