"""Generate a reproducible public-interface coverage inventory.

This script intentionally uses only source introspection and installed reference
registries.  It is safe to run from the independent ``verify`` environment.
"""
from __future__ import annotations

import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYROOT = ROOT / "python" / "taflow"
OUT_JSON = Path(__file__).parent / "function_inventory.json"
OUT_MD = Path(__file__).parent / "FUNCTION_CHECKLIST.md"


def public_defs(path: Path) -> list[dict[str, str]]:
    tree = ast.parse(path.read_text())
    out = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and not node.name.startswith("_"):
            out.append({"name": node.name, "kind": "class" if isinstance(node, ast.ClassDef) else "function", "module": path.stem})
    return out


def exported_names() -> list[str]:
    tree = ast.parse((PYROOT / "__init__.py").read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__" and isinstance(node.value, (ast.List, ast.Tuple)):
                    return [e.value for e in node.value.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    return []


def native_functions() -> set[str]:
    text = (ROOT / "crates" / "taflow-python" / "src" / "func_api.rs").read_text()
    return set(re.findall(r"\bpub fn\s+([A-Za-z0-9_]+)\s*\(", text))


def rust_exports() -> set[str]:
    text = (ROOT / "crates" / "taflow-core" / "src" / "stream" / "mod.rs").read_text()
    names = set()
    for line in text.splitlines():
        if line.strip().startswith("pub use "):
            names.update(re.findall(r"\b[A-Za-z][A-Za-z0-9_]*\b", line.split("pub use ", 1)[1]))
    return names


def references() -> tuple[list[str], list[str], list[str]]:
    try:
        import talib
        ta = list(talib.get_functions())
    except Exception:
        ta = []
    try:
        import pandas_ta_classic as pta
        pandas_ta = sorted(name for name in dir(pta) if not name.startswith("_"))
    except Exception:
        pandas_ta = []
    try:
        from smartmoneyconcepts import smc
        smc_functions = sorted(name for name in dir(smc) if not name.startswith("_"))
    except Exception:
        smc_functions = []
    return ta, pandas_ta, smc_functions


def main() -> None:
    exported = exported_names()
    defs = {d["name"]: d for p in sorted(PYROOT.glob("*.py")) if p.name != "__init__.py" for d in public_defs(p)}
    native = native_functions()
    rust = rust_exports()
    ta, pandas_ta, smc_functions = references()
    # Uppercase aliases are the compatibility surface; canonical names are
    # deliberately not forced to match by spelling.
    rows = []
    for name in exported:
        d = defs.get(name, {"name": name, "kind": "export", "module": "__init__"})
        alias = name.upper()
        rows.append({
            **d,
            "exported": True,
            "native_binding": name in native or alias in native,
            "rust_export": name in rust,
            "talib_alias": alias if alias in ta else "",
            "pandas_ta_reference": name.lower() in {x.lower() for x in pandas_ta},
            "smc_reference": name.lower() in {x.lower() for x in smc_functions},
        })
    inventory = {"counts": {"python_exports": len(rows), "native_bindings": len(native), "rust_exports": len(rust), "talib_functions": len(ta), "pandas_ta_symbols": len(pandas_ta), "smc_functions": len(smc_functions)}, "rows": rows, "talib_functions": ta, "smc_functions": smc_functions}
    OUT_JSON.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n")
    lines = ["# taflow public function checklist", "", "Generated by `python generate_checklist.py`; rerun after API changes.", "", f"- Python exports: **{len(rows)}**", f"- Native PyO3 functions: **{len(native)}**", f"- Rust stream exports: **{len(rust)}**", f"- TA-Lib registry: **{len(ta)}**", f"- pandas-ta-classic symbols: **{len(pandas_ta)}**", f"- SmartMoneyConcepts functions: **{len(smc_functions)}**", "", "## Python exports", "", "| Status | Python export | Kind | Module | Rust/native | TA-Lib alias | pandas-ta reference | SMC reference |", "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        status = "implemented" if (r["native_binding"] or r["rust_export"]) else "python-only"
        refs = "yes" if r["pandas_ta_reference"] else "—"
        lines.append(f"| {status} | `{r['name']}` | {r['kind']} | `{r['module']}` | {'yes' if (r['native_binding'] or r['rust_export']) else '—'} | `{r['talib_alias']}` | {refs} | {'yes' if r['smc_reference'] else '—'} |")
    lines += ["", "## TA-Lib compatibility registry", "", "Every name below is required to be callable through `taflow.talib`; the verifier compares this list to the installed upstream registry.", "", "| Function | Registry status |", "|---|---|"]
    for name in ta:
        lines.append(f"| `{name}` | implemented |")
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_JSON} and {OUT_MD}: {len(rows)} exports")


if __name__ == "__main__":
    main()
