#!/usr/bin/env python3
"""Regenerate the shared Python and Rust indicator API reference.

Python signatures are introspected from the live classes and Rust constructor
signatures are read from the canonical implementation files. TA-Lib names and
ordered input lists come from the verification registry.

    python scripts/gen_indicators_doc.py
"""

import inspect
import pathlib
import re

from verification.registry import build_registry

ROOT = pathlib.Path(__file__).resolve().parent.parent
SERIES = {
    "_input",
    "values",
    "price",
    "close",
    "high",
    "low",
    "open",
    "_open",
    "volume",
    "real",
    "input",
    "series",
    "x",
    "y",
    "periods",
    "condition",
    "new_session",
    "session_id",
}

def load_metadata():
    """Return canonical indicator metadata from the verification registry."""
    return {
        spec.cls.__name__: {
            "class": spec.cls,
            "talib": spec.talib_name,
            "inputs": list(spec.series_args),
        }
        for spec in build_registry().values()
    }


def python_signature(callable_object, *, drop_self=False):
    """Return a complete public signature without the return annotation."""

    try:
        signature = inspect.signature(callable_object, eval_str=True)
    except (TypeError, ValueError):
        return "—"
    if drop_self:
        parameters = tuple(signature.parameters.values())
        if parameters and parameters[0].name == "self":
            signature = signature.replace(parameters=parameters[1:])
    rendered = str(signature)
    return rendered.rsplit(" -> ", 1)[0]


def snake_case(name):
    """Derive the canonical module filename from a full class name."""

    first = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", first).lower()


def rust_method_signature(class_name, method_name):
    """Read one exact method parameter list from a canonical Rust class."""

    path = (
        ROOT
        / "crates"
        / "taflow-core"
        / "src"
        / "indicators"
        / f"{snake_case(class_name)}.rs"
    )
    if not path.exists():
        return "—"
    source = path.read_text()
    visibility = r"pub\s+" if method_name == "new" else r"(?:pub\s+)?"
    match = re.search(
        rf"{visibility}fn\s+{re.escape(method_name)}\s*\(", source
    )
    if match is None:
        return "—"
    start = source.index("(", match.start())
    depth = 0
    end = None
    for index in range(start, len(source)):
        if source[index] == "(":
            depth += 1
        elif source[index] == ")":
            depth -= 1
            if depth == 0:
                end = index
                break
    if end is None:
        raise ValueError(f"unclosed {method_name} signature in {path}")
    parameters = re.sub(r"\s+", " ", source[start + 1 : end]).strip()
    parameters = re.sub(r"\s*,\s*", ", ", parameters)
    parameters = parameters.rstrip(", ")
    return f"{method_name}({parameters})"


def code(value):
    """Render one Markdown table cell as inline code."""

    escaped = value.replace("|", "\\|")
    return f"`{escaped}`"


def main():
    meta = load_metadata()
    rows = []
    for name in sorted(meta):
        cls = meta[name]["class"]
        rows.append(
            {
                "cls": name,
                "talib": meta[name]["talib"],
                "inputs": ", ".join(meta[name]["inputs"]) or "—",
                "python_constructor": python_signature(cls),
                "python_append": python_signature(cls.append, drop_self=True),
                "python_extend": python_signature(cls.extend, drop_self=True),
                "rust_constructor": rust_method_signature(name, "new"),
                "rust_append": rust_method_signature(name, "append"),
            }
        )

    talib_n = sum(1 for r in rows if r["talib"])

    out = [
        "# TAFlow indicator reference\n",
        f"**{len(rows)}** classes — **{talib_n}** with a TA-Lib equivalent, "
        f"**{len(rows) - talib_n}** extended operators with no TA-Lib counterpart.\n",
        "> Generated by `scripts/gen_indicators_doc.py` from the installed package. "
        "Do not edit by hand.\n",
        "Classes are sorted alphabetically by their full canonical names. Python "
        "signatures are introspected from the installed adapters; Rust signatures "
        "come from each canonical implementation file. Python defaults are shown "
        "verbatim. Rust has no default arguments, so every Rust constructor "
        "parameter is explicit.\n",
        "## Python usage\n",
        """Every class behaves the same way:

```python
from taflow import SimpleMovingAverage

ind = SimpleMovingAverage(timeperiod=30)         # configuration only
ind.extend(close)                                # historical backfill
ind.append(float(close[-1]))                     # O(1) live update
ind.value                                        # latest value, None during warm-up
ind.compute()                                    # full aligned series
len(ind)                                         # bars consumed
ind.reset()                                      # clear state and history in place
```

Outputs are `float64` arrays the same length as the input, `NaN` through
warm-up. Multi-output indicators return a tuple. Candle patterns return
`int32` scores (`0`, `±100`).
""",
        "## Rust usage\n",
        """```rust
use taflow::indicators::SimpleMovingAverage;
use taflow::stream::StreamingIndicator;

fn calculate_simple_moving_average(
    close: &[f64],
) -> taflow::TaResult<Vec<f64>> {
    let mut simple_moving_average = SimpleMovingAverage::new(30)?;
    let mut output = Vec::with_capacity(close.len());
    simple_moving_average.extend_slice_into(close, &mut output);
    Ok(output)
}
```

Rust constructors require every configuration parameter. Single-input classes
implement `StreamingIndicator`; multi-input and multi-output classes expose
equivalent inherent `append`, `value`, `reset`, and bulk methods.
""",
        "## Parameter reference contract\n",
        """Every constructor accepts configuration only. Historical series are
passed to ``extend`` in the documented input order. Configuration values have
defaults unless the algorithm cannot define one semantically:

```python
from taflow import SimpleMovingAverage, MoneyFlowIndex

SimpleMovingAverage(timeperiod=30).extend(close)
MoneyFlowIndex(timeperiod=14).extend(high, low, close, volume)
```

The Python constructor, `append`, and `extend` columns contain the complete public
parameter lists, including annotations, keyword-only markers, and default
values. The Rust constructor and `append` columns contain their exact explicit
parameters. Passing Python data by keyword always works.
""",
        "## Alphabetical class reference\n",
        "| Class | External name | Input order | Python constructor | Python `append` | Python `extend` | Rust constructor | Rust `append` |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        out.append(
            f"| `{row['cls']}` | {row['talib'] or '—'} | `({row['inputs']})` | "
            f"{code(row['python_constructor'])} | {code(row['python_append'])} | "
            f"{code(row['python_extend'])} | {code(row['rust_constructor'])} | "
            f"{code(row['rust_append'])} |"
        )
    out.append("")

    target = ROOT / "docs/INDICATORS.md"
    target.write_text("\n".join(out))
    print(f"wrote {target.relative_to(ROOT)}: {len(rows)} classes, {talib_n} TA-Lib")


if __name__ == "__main__":
    main()
